In [9]:
#Import library 
import numpy as np

#create a function called cofactor that takes 3 inputs: 5x5 matrix, rows and columns

def cofactor(matrix, row, col):
    # Check if the input matrix is 5x5
    if matrix.shape != (5, 5):
        raise ValueError("Input matrix must be 5x5.")
    
    # Extract the specified row and column
    sub_matrix = np.delete(np.delete(matrix, row, axis=0), col, axis=1)
    print(sub_matrix)
    
    # Compute the determinant of the 4x4 sub_matrix
    det = np.linalg.det(sub_matrix)
    
    print('The determinant of the submatrix is:',det)
    
    # Returns the cofactor
    return (-1)**(row + col) * det

# Sample 5x5 matrix
matrix = np.array([[9, 2, -3, 8, 1],[0, 7, -7, 8, 2],[-2, 0, -4, 5, 5],[1, 9, -5, 7, 7],[3, 5, 2, 0, 9]])

#Extracts the A3,2 element which is the element in the 3rd row and 2nd column

M = matrix[2][1]

print(f"Value of A3,2 element: {M}")

print(cofactor(matrix, 2, 1))


Value of A3,2 element: 0
[[ 9 -3  8  1]
 [ 0 -7  8  2]
 [ 1 -5  7  7]
 [ 3  2  0  9]]
The determinant of the submatrix is: -199.99999999999991
199.99999999999991
